### PR TITLE
Python 3.8, 3.10, and 3.12 support

### PR DESCRIPTION
**Pull request by mahnunchik**
I'm working on adding support for python `3.8`, `3.10`, and `3.12`.

Motivation: Home Assistant addon uses python 3.11, so I decided to make `mqtt-io` working with latest `3.12` too.

I successfully upgraded to 3.10. But to work on 3.12, I had to update `pylint` and `mypy` packages. I fixed most of the lint errors but I need a help to figure it out last two errors:

```
poetry run mypy --show-error-codes --strict --no-warn-unused-ignores mqtt_io
mqtt_io/modules/gpio/gpiozero.py:99: error: Argument 1 has incompatible type "bool"; expected "list[Any]"  [arg-type]
mqtt_io/modules/gpio/gpiozero.py:101: error: Argument 1 has incompatible type "bool"; expected "list[Any]"  [arg-type]
Found 2 errors in 1 file (checked 61 source files)
```

Sources: https://github.com/flyte/mqtt-io/blob/ad8514cd1131a75fc6dec289b4ca2a3c03722532/mqtt_io/modules/gpio/gpiozero.py#L99-L101

CI: https://github.com/mahnunchik/mqtt-io/actions/runs/11000870597

### CODE REVIEW

**Comment by mahnunchik** [comment]
@flyte @mschlenstedt @BenjiU could you please help me to solve last two issues with `mypy` linting.

**Comment by mahnunchik** [comment]
@flyte @mschlenstedt @BenjiU I was able to resolve the last type validation error: to support any list of arguments `Callable` should have signature `[Callable[..., None]]` instead of `Callable[[List[Any], Dict[Any, Any]]`.

* https://docs.python.org/3/library/typing.html#annotating-callable-objects
* https://github.com/python/mypy/blob/master/CHANGELOG.md#support-for-functoolspartial

Summary of this PR:
* `mypy` updated to support python 3.11+
* `pylint` updated to support python 3.9+
* `backoff` updated to support typing out of the box
* Updated github action
* Many typing fixes

I'd like to request to review my PR.

**Review by BenjiU — APPROVED** [review]
Thanks for this great contribution
